export const GET_SEARCH_RESULT_REQUEST = 'GET_SEARCH_RESULT_REQUEST'
export const GET_SEARCH_RESULT_SUCCESS = 'GET_SEARCH_RESULT_SUCCESS'
export const GET_SEARCH_RESULT_ERROR = 'GET_SEARCH_RESULT_ERROR'

export const GET_ARTIST_REQUEST = 'GET_ARTIST_REQUEST'
export const GET_ARTIST_SUCCESS = 'GET_ARTIST_SUCCESS'
export const GET_ARTIST_ERROR = 'GET_ARTIST_ERROR'
